FROM --platform=$TARGETPLATFORM docker.io/busybox:latest

RUN mkdir static
COPY static static
# these are generated by wasm-pack
RUN rm static/pkg/.gitignore static/pkg/package.json

EXPOSE 9898/tcp
RUN echo "E404:index.html" > /etc/httpd.conf
ENTRYPOINT ["httpd", "-f", "-p", "0.0.0.0:9898", "-h", "/static", "-c", "/etc/httpd.conf"]
