kind: Service
apiVersion: v1
metadata:
  name: homepage
  namespace: homepage
spec:
  selector:
    deployment: homepage
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9898
    targetPort: 9898
    
